# Generated by Django 5.2.1 on 2025-06-01 03:40

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/media', validators=[store.validators.validate_file_size]),
        ),
    ]
