# Generated by Django 6.1 on 2026-08-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_orders_orde_custome_7b68ab_idx_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', '-created_at'], name='payment_pay_order_i_c315bf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'),
        ),
    ]
