# Generated by Django 6.1 on 2026-08-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_payment_pay_order_i_c315bf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack')], default='PAYSTACK', max_length=20),
        ),
    ]
