# Generated by Django 6.1 on 2026-08-21 21:34

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3),
        ),
    ]
