# Generated by Django 6.1 on 2026-08-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_reason', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.orderitem')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='returns_ret_status_e1e871_idx'), models.Index(fields=['-requested_at'], name='returns_ret_request_c0a6af_idx')],
            },
        ),
    ]
