# Generated by Django 6.1 on 2026-08-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='resolution_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='return',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
