# Generated by Django 6.1 on 2026-08-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_orders_orde_custome_7b68ab_idx_and_more'),
        ('returns', '0002_return_resolution_reason_return_reviewed_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status'], name='returns_ret_status_e1e871_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['-requested_at'], name='returns_ret_request_c0a6af_idx'),
        ),
    ]
