# Generated by Django 6.1 on 2026-08-09 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='likeditem',
            index=models.Index(fields=['content_type', 'object_id'], name='likes_liked_content_7292dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='likeditem',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_like_per_user_object'),
        ),
    ]
