# Generated by Django 6.1 on 2026-08-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.variant'),
        ),
        migrations.AddField(
            model_name='variantaxisvalue',
            name='axis_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_links', to='catalog.axisvalue'),
        ),
        migrations.AddField(
            model_name='variantaxisvalue',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_values', to='catalog.variant'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='catalog_pro_status_521020_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['collection', 'status'], name='catalog_pro_collect_708cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-last_update'], name='catalog_pro_last_up_4dbed3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', '-date'], name='catalog_rev_product_d83ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(condition=models.Q(('track_inventory', True)), fields=['track_inventory', 'inventory', 'allocated'], name='variant_in_stock_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(condition=models.Q(('axis_value__isnull', True), ('variant__isnull', True), _connector='OR'), name='productimage_axis_value_or_variant_not_both'),
        ),
        migrations.AddConstraint(
            model_name='variantaxisvalue',
            constraint=models.UniqueConstraint(fields=('variant', 'axis_value'), name='unique_variant_axis_value'),
        ),
    ]
