# Generated by Django 6.1 on 2026-08-08 11:14

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=6, validators=[djmoney.models.validators.MinMoneyValidator(1)]),
        ),
    ]
