# Generated by Django 6.0.8 on 2026-08-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='productimage_axis_value_or_variant_not_both',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='axis_value',
        ),
    ]
