# Generated by Django 6.0.8 on 2026-08-24 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_productimage_productimage_axis_value_or_variant_not_both_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'vocabularies',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['vocabulary__key', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='axisvalue',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productaxis',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='axes', to='catalog.vocabulary'),
        ),
        migrations.AddConstraint(
            model_name='productaxis',
            constraint=models.UniqueConstraint(fields=('product', 'vocabulary'), name='unique_product_axis_vocabulary'),
        ),
        migrations.AddField(
            model_name='vocabularyvalue',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.vocabulary'),
        ),
        migrations.AddField(
            model_name='axisvalue',
            name='vocabulary_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='axis_values', to='catalog.vocabularyvalue'),
        ),
        migrations.AddConstraint(
            model_name='axisvalue',
            constraint=models.UniqueConstraint(fields=('axis', 'vocabulary_value'), name='unique_axis_vocabulary_value'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyvalue',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'value'), name='unique_vocabulary_value'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('vocabulary', 'code'), name='unique_vocabulary_code'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyvalue',
            constraint=models.CheckConstraint(condition=models.Q(('label', ''), _negated=True), name='vocabulary_value_label_not_blank'),
        ),
    ]
