# Generated by Django 6.1 on 2026-08-08 20:07

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_variant_productaxis_axisvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='compare_at_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
