# Generated by Django 6.1 on 2026-08-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_variant_compare_at_price_currency'),
        ('customers', '0002_customer_customers_c_members_fac1cd_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='catalog_pro_status_521020_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['collection', 'status'], name='catalog_pro_collect_708cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-last_update'], name='catalog_pro_last_up_4dbed3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', '-date'], name='catalog_rev_product_d83ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(condition=models.Q(('track_inventory', True)), fields=['track_inventory', 'inventory'], name='variant_in_stock_idx'),
        ),
    ]
