# Generated by Django 6.1 on 2026-08-18 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='variant',
            name='variant_in_stock_idx',
        ),
        migrations.AddField(
            model_name='variant',
            name='allocated',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(condition=models.Q(('track_inventory', True)), fields=['track_inventory', 'inventory', 'allocated'], name='variant_in_stock_idx'),
        ),
    ]
