# Generated by Django 6.1 on 2026-08-21 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_variant_variant_in_stock_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='axis_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.axisvalue'),
        ),
    ]
