# Generated by Django 6.1 on 2026-08-21 21:34

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productimage_axis_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='compare_at_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='unit_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3),
        ),
    ]
