# Generated by Django 6.1 on 2026-08-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_variant_compare_at_price_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAxisValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_links', to='catalog.axisvalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_values', to='catalog.variant')),
            ],
            options={
                'ordering': ['axis_value__axis__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('variant', 'axis_value'), name='unique_variant_axis_value')],
            },
        ),
    ]
