# Generated by Django 6.1 on 2026-08-21 22:16

import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_variantaxisvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
