# Generated by Django 6.1 on 2026-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productimage_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(condition=models.Q(('axis_value__isnull', True), ('variant__isnull', True), _connector='OR'), name='productimage_axis_value_or_variant_not_both'),
        ),
    ]
