# Generated by Django 6.1 on 2026-08-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_variant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['last_activity'], name='cart_cart_last_ac_251660_idx'),
        ),
    ]
