# Generated by Django 6.1 on 2026-08-21 18:57

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_user_cart_unique_active_cart_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_at_add',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_at_add_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
