# Generated by Django 6.1 on 2026-08-21 21:34

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_price_at_add_cartitem_price_at_add_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_add_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3, null=True),
        ),
    ]
