# Generated by Django 6.1 on 2026-08-22 20:41

import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('DAWUROBO', 'Dawurobo')], default='DAWUROBO', max_length=20)),
                ('tracking_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=100)),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'GHS'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('DISPATCHED', 'Dispatched'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('DELIVERY_FAILED', 'Delivery Failed')], default='PENDING', max_length=20)),
                ('booking_failed', models.BooleanField(default=False)),
                ('estimated_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='shipping_sh_order_i_cb7c84_idx'), models.Index(fields=['status'], name='shipping_sh_status_0644c6_idx')],
            },
        ),
    ]
