# Generated by Django 6.1 on 2026-08-21 21:34

import djmoney.models.fields
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'GHS'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3),
        ),
    ]
