# Generated by Django 6.1 on 2026-08-22 20:41

import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_token', models.CharField(default=orders.models.generate_guest_token, editable=False, max_length=43, unique=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('CONFIRMED', 'Confirmed'), ('FULFILLMENT', 'Fulfillment'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('PENDING_RESOLUTION', 'Pending Resolution'), ('CANCELLED', 'Cancelled')], default='', max_length=19)),
                ('fulfillment_method', models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], max_length=8)),
                ('subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3)),
                ('subtotal', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'GHS'), max_digits=10)),
                ('shipping_cost_currency', djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3)),
                ('shipping_cost', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'GHS'), max_digits=10)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
            ],
            options={
                'permissions': [('cancel_order', 'Can cancel order')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price_currency', djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3)),
                ('unit_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='catalog.variant')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-placed_at'], name='orders_orde_custome_7b68ab_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fulfillment_method'], name='orders_orde_fulfill_d0c1ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('customer__isnull', False), ('shipping_address__isnull', False), _connector='OR'), name='order_has_customer_or_guest_contact'),
        ),
    ]
