# Generated by Django 6.1 on 2026-08-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('CONFIRMED', 'Confirmed'), ('FULFILLMENT', 'Fulfillment'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('PENDING_RESOLUTION', 'Pending Resolution'), ('CANCELLED', 'Cancelled')], default='', max_length=19),
        ),
    ]
