# Generated by Django 6.1 on 2026-08-19 06:50

import djmoney.models.fields
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_orders_orde_custome_7b68ab_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'USD'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
