# Generated by Django 6.1 on 2026-08-19 19:49

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_shipping_cost_order_shipping_cost_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_option_token',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
