# Generated by Django 6.1 on 2026-08-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customers_c_members_fac1cd_idx'),
        ('orders', '0013_remove_order_shipping_option_token_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_has_customer_or_guest_contact',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_guest_e_5522f9_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='guest_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='guest_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='guest_phone',
            new_name='phone',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='orders_orde_email_88c705_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('customer__isnull', False), models.Q(models.Q(('email', ''), _negated=True), models.Q(('name', ''), _negated=True)), _connector='OR'), name='order_has_customer_or_guest_contact'),
        ),
    ]
