# Generated by Django 6.1 on 2026-08-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customers_c_members_fac1cd_idx'),
        ('orders', '0014_rename_guest_contact_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_has_customer_or_guest_contact',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_email_88c705_idx',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('customer__isnull', False), ('shipping_address__isnull', False), _connector='OR'), name='order_has_customer_or_guest_contact'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
