# Generated by Django 6.1 on 2026-08-21 21:34

import djmoney.models.fields
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_drop_guest_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'GHS'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'GHS'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'Ghanaian Cedi')], default='GHS', editable=False, max_length=3),
        ),
    ]
