# Generated by Django 6.1 on 2026-08-22 16:45

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_token',
            field=models.CharField(default=orders.models.generate_guest_token, editable=False, max_length=43, unique=True),
        ),
    ]
