# Generated by Django 6.1 on 2026-08-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('SHIPMENT_DISPATCHED', 'Shipment Dispatched'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('DELIVERY_FAILED', 'Delivery Failed'), ('REFUND_DECISION', 'Refund Decision')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['order', '-sent_at'], name='notificatio_order_i_c74624_idx'), models.Index(fields=['event_type'], name='notificatio_event_t_c22bab_idx')],
            },
        ),
    ]
