# Generated by Django 6.1 on 2026-08-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0010_order_orders_orde_custome_7b68ab_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['order', '-sent_at'], name='notificatio_order_i_c74624_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type'], name='notificatio_event_t_c22bab_idx'),
        ),
    ]
