# Generated by Django 6.1 on 2026-08-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificatio_order_i_c74624_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('SHIPMENT_DISPATCHED', 'Shipment Dispatched'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('DELIVERY_FAILED', 'Delivery Failed'), ('REFUND_DECISION', 'Refund Decision')], max_length=20),
        ),
    ]
